- name: Create a container directory if it does not exist
  ansible.builtin.file:
    path: ~/containers
    state: directory
    mode: '0755'

- name: copy shellscript to ~/bin
  ansible.builtin.copy:
    src: ~/ansible-install-docker/files/mkdir_containers.sh
    dest: ~/bin/mkdir_containers.sh
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755

- name: Execute the mkdirs for *arr applications; stdout goes to the specified file on the remote
  shell: sh ~/bin/mkdir_containers.sh >> make_containers_dirs.txt

- name: Copy prowlarr-compose.yml
  ansible.builtin.copy:
    src: prowlarr-compose.yml
    dest: ~/containers/prowlarr/docker-compose.yml
    group: "{{ user }}"
    owner: "{{ user }}"
    mode: 0775

- name: Copy check_prowlarr_status.sh to ~/containers/prowlarr
  ansible.builtin.copy:
    src: check_prowlarr_status.sh
    dest: ~/containers/prowlarr/check_prowlarr_status.sh
    group: "{{ user }}"
    owner: "{{ user }}"
    mode: 0775

- name: Copy radarr-compose.yml
  ansible.builtin.copy:
    src: radarr-compose.yml
    dest: ~/containers/radarr/docker-compose.yml
    group: "{{ user }}"
    owner: "{{ user }}"
    mode: 0775

- name: Copy check_radarr_status.sh to ~/containers/radarr
  ansible.builtin.copy:
    src: check_radarr_status.sh
    dest: ~/containers/radarr/check_radarr_status.sh
    group: "{{ user }}"
    owner: "{{ user }}"
    mode: 0775

- name: Copy sonarr-compose.yml
  ansible.builtin.copy:
    src: sonarr-compose.yml
    dest: ~/containers/sonarr/docker-compose.yml
    group: "{{ user }}"
    owner: "{{ user }}"
    mode: 0775

- name: Copy check_sonarr_status.sh to ~/containers/sonarr
  ansible.builtin.copy:
    src: check_sonarr_status.sh
    dest: ~/containers/sonarr/check_sonarr_status.sh
    group: "{{ user }}"
    owner: "{{ user }}"
    mode: 0775

- name: Copy sabnzbd-compose.yml
  ansible.builtin.copy:
    src: sabnzbd-compose.yml
    dest: ~/containers/sabnzbd/docker-compose.yml
    group: "{{ user }}"
    owner: "{{ user }}"
    mode: 0775

- name: Copy check_sabnzbd_status.sh to ~/containers/sabnzbd
  ansible.builtin.copy:
    src: check_sabnzbd_status.sh
    dest: ~/containers/sabnzbd/check_sabnzbd_status.sh
    group: "{{ user }}"
    owner: "{{ user }}"
    mode: 0775

- name: Copy qbittorrent-compose.yml
  ansible.builtin.copy:
    src: qbittorrent-compose.yml
    dest: ~/containers/qbittorrent/docker-compose.yml
    group: "{{ user }}"
    owner: "{{ user }}"
    mode: 0775

- name: Copy check_qbittorrent_status.sh to ~/containers/qbittorrent
  ansible.builtin.copy:
    src: check_qbittorrent_status.sh
    dest: ~/containers/qbittorrent/check_qbittorrent_status.sh
    group: "{{ user }}"
    owner: "{{ user }}"
    mode: 0775

- name: check if prowlarr container is running
  shell: sh ~/containers/prowlarr/check_prowlarr_status.sh

- name: check if radarr container is running
  shell: sh ~/containers/radarr/check_radarr_status.sh

- name: check if sonarr container is running
  shell: sh ~/containers/sonarr/check_sonarr_status.sh

- name: check if qbittorrent container is running
  shell: sh ~/containers/qbittorrent/check_qbittorrent_status.sh

- name: check if sabnzbd container is running
  shell: sh ~/containers/sabnzbd/check_sabnzbd_status.sh
