- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/serge/docker
    state: directory
    mode: '0755'

- name: Copy install_portainer file
  ansible.builtin.copy:
    src: install_portainer.sh
    dest: /home/serge/bin
    owner: serge
    group: serge
    mode: 0700

- name: Copy update_portainer file
  ansible.builtin.copy:
    src: update_portainer.sh
    dest: /home/serge/bin
    owner: serge
    group: serge
    mode: 0700

- name: Copy reinstall_portainer file
  ansible.builtin.copy:
    src: reinstall_portainer.sh
    dest: /home/serge/bin
    owner: serge
    group: serge
    mode: 0700

- name: Install portainer on remote host 
  shell: sh /home/serge/bin/install_portainer.sh
  when: ansible_distribution == "Debian"

